### ISSUE TITLE
"Could not converge" for anything more than a few cashflows

### ISSUE THREAD

**Issue by michaelbridge** [tubedude/finance-elixir#6]
Running on a local app, tests with shorter cashflow histories (i.e., below) succeed.

```
d = [{1985, 1, 1}, {1990, 1, 1}, {1995, 1, 1}]
v = [1000, -600, -200]
IO.inspect Finance.xirr(d,v)
```

But longer cashflow inputs that are known to converge in Ruby, Javascript, and Excel always return {:error, "Could not converge"}.

Any insights/tips as to why this occurs with the current implementation?  I would consider opening a PR with improvements if I can get to the bottom of this.

@elionaz @tubedude

**Comment by tubedude** [comment]
@michaelbridge Can you send me an example of a cashflow that fails?

**Comment by michaelbridge** [comment]
Almost any input with >30 cashflows.

Thank you, but I ended up writing my own xirr library for Node.js, which turns out to be substantially faster for our purposes than elixir (notwithstanding elixir's concurrency benefits).
